// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: b.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type B struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           *LoginRequest          `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *B) Reset() {
	*x = B{}
	mi := &file_b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B) ProtoMessage() {}

func (x *B) ProtoReflect() protoreflect.Message {
	mi := &file_b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B.ProtoReflect.Descriptor instead.
func (*B) Descriptor() ([]byte, []int) {
	return file_b_proto_rawDescGZIP(), []int{0}
}

func (x *B) GetAge() *LoginRequest {
	if x != nil {
		return x.Age
	}
	return nil
}

var File_b_proto protoreflect.FileDescriptor

const file_b_proto_rawDesc = "" +
	"\n" +
	"\ab.proto\x1a\aa.proto\"0\n" +
	"\x01B\x12+\n" +
	"\x03age\x18\x01 \x01(\v2\x19.idl.service.LoginRequestR\x03ageB\x1aZ\x18idl/service;user_serviceb\x06proto3"

var (
	file_b_proto_rawDescOnce sync.Once
	file_b_proto_rawDescData []byte
)

func file_b_proto_rawDescGZIP() []byte {
	file_b_proto_rawDescOnce.Do(func() {
		file_b_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_b_proto_rawDesc), len(file_b_proto_rawDesc)))
	})
	return file_b_proto_rawDescData
}

var file_b_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_b_proto_goTypes = []any{
	(*B)(nil),            // 0: B
	(*LoginRequest)(nil), // 1: idl.service.LoginRequest
}
var file_b_proto_depIdxs = []int32{
	1, // 0: B.age:type_name -> idl.service.LoginRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_b_proto_init() }
func file_b_proto_init() {
	if File_b_proto != nil {
		return
	}
	file_a_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_b_proto_rawDesc), len(file_b_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_b_proto_goTypes,
		DependencyIndexes: file_b_proto_depIdxs,
		MessageInfos:      file_b_proto_msgTypes,
	}.Build()
	File_b_proto = out.File
	file_b_proto_goTypes = nil
	file_b_proto_depIdxs = nil
}
